[package]
name = "labelview"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
cbor4ii = { version = "0.3.3", features = ["use_std"] }
clap = { version = "4.5.21", features = ["derive"] }
directories = "5.0.1"
futures-util = "0.3.31"
libsqlite3-sys = { version = "0.30.1", features = ["bundled"] } # TODO(widders): custom bundle
rustls = "0.23.18" # default features
sqlx = { version = "0.8.2", features = ["macros", "runtime-tokio", "sqlite"] }
tokio = { version = "1.41.1", features = ["io-util", "net", "rt", "rt-multi-thread", "macros"] }
tokio-tungstenite = { version = "0.24.0", features = ["connect", "rustls-tls-native-roots", "url"] }
url = "2.5.4"
