[package]
name = "labelview"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
atrium-api = "0.24.8"
clap = { version = "*", features = ["derive"] }
rustls = "0.23.18"
tokio = { version = "1.41.1", features = ["io-util", "net", "rt", "rt-multi-thread", "macros"] }
tokio-tungstenite = { version = "0.24.0", features = ["connect", "rustls-tls-native-roots", "url"] }
url = "2.5.4"
